### ISSUE TITLE
I cannot get the dataset. Can you help me?

### ISSUE THREAD

**Issue by NAM-hj** [serwy/aplawdw#1]
Hi, 
thank you for your nice work.

I tried to get the dataset from the link. But I cannot download it.
(https://www.commsp.ee.ic.ac.uk/~sap/resources/aplawdw/)

It links to "HTTP Error 404. The requested resource is not found." page.

Thank you.

**Comment by serwy** [comment]
The dataset is available at that URL. It may be that the site was momentarily offline.

**Comment by serwy** [comment]
It appears that their link is broken. It can be found here: https://www.commsp.ee.ic.ac.uk/~sap/uploads/data/aplawdw.zip
